apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployment
  labels:
    app: agent
spec:
  selector:
    matchLabels:
      app: agent
  replicas: 2
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: agent
          image: dineshsivan169/dineshdemo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: agentsec
	  livenessProbe:
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
        initialDelaySeconds: 10
          # How often (in seconds) to perform the probe.
        periodSeconds: 5
          # Amount of time to wait before timing out
        timeoutSeconds: 1
          # Kubernetes will try failureThreshold times before giving up and restarting the Pod
        failureThreshold: 2
          # Probe for http
        httpGet:
            # Path to probe
          path: /
            # Port to probe
          port: 90
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: agentservice
  labels:
    app: agent
spec:
  selector:
    app: agent
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer