apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: agent-deployment
  labels:
    app: agent
spec:
  selector:
    matchLabels:
      app: agent
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: agent
        tier: backend
    spec:
      containers:
      - name: agent
        image: dineshsivan169/dineshdemo
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: agent-service
  labels:
    app: agent 
spec:
  selector:
    app: agent 

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer