apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployment
  labels:
    app: agent
spec:
  selector:
    matchLabels:
      app: agent
  replicas: 2
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: agent
          image: dineshsivan169/dineshdemo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: agentsec
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: agentservice
  labels:
    app: agent
spec:
  selector:
    app: agent
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer